### ISSUE TITLE
 Module did not self-register

### ISSUE THREAD

**Issue by pyrocto** [jerch/node-termios#13]
I'm trying to use node-termios in edex-ui to turn off the on-screen keyboard when ECHO is disabled.  However, as soon as I `require` the module, it throws this error:
```
(node:45470) UnhandledPromiseRejectionWarning: Error: Module did not self-register: '/Users/stay/random/edex-ui/src/node_modules/node-termios/build/Release/termios.node'.
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/stay/random/edex-ui/src/node_modules/node-termios/lib/index.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
(Use `Electron --trace-warnings ...` to show where the warning was created)
(node:45470) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:45470) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The advice on [StackOverflow](https://stackoverflow.com/questions/28486891/uncaught-error-module-did-not-self-register) was to delete the `node_modules` directory and reinstall.  I tried that with no effect.  Any other advice?

**Comment by jerch** [comment]
@pyrocto Hmm this is a very generic error telling that some promise got rejected but not caught, not very helpful as it masks the real error that caused the rejection.

Two things come to my mind, why the module cannot be loaded:
- NODE_MODULE_VERSION mismatch of electron and node-termios
- you required the module in browser context without the flag for nodejs modules

How and in which context did you try to require the module (server side or browser context)?

**Comment by pyrocto** [comment]
Thanks for the edit!  That did it.  I added
```./../node_modules/.bin/electron-rebuild -f -w node-termios```
and it runs fine.
